import random

MAX_LINES = 3
MAX_BET = 100        # Here capitals are constants...
MIN_BET = 30

ROWS = 3
COLS = 3

print("*****Welcome to Slot machine!!!*****")

symbol_count = {
    'A': 2,
    'B': 4,
    'C': 6,
    'D': 8
}

symbol_value = {
    'A': 5,
    'B': 4,
    'C': 3,
    'D': 2
}


# ............................................................
# These functions are Generated by AI

def get_slot_machine_spin(rows, cols, symbols):
    # This func is for spin for symbol count
    all_symbols = []

    for symbol, symbol_count in symbols.items():
        for _ in range(symbol_count):
            all_symbols.append(symbol)

    columns = []

    for _ in range(cols):
        column = []
        current_symbols = all_symbols[:]

        for _ in range(rows):
            value = random.choice(current_symbols)
            current_symbols.remove(value)
            column.append(value)

        columns.append(column)

    return columns


def print_slot_machine(columns):
    # This func is called for transpose the given matrix
    for row in range(len(columns[0])):
        for i, column in enumerate(columns):
            if i != len(columns) - 1:
                print(column[row], end="  |  ")
            else:
                print(column[row], end="")

        print()


# .............................................................


def deposit():
    while True:
        amount = input("Enter your deposit: $")

        # blud we can do directly but if the value is not int
        # then it gives error in int(input())
        if amount.isdigit():
            amount = int(amount)

            if amount > 0:
                break
            else:
                print("Amount should be greater than 0!")
        else:
            print("Amount should be entered as numbers")

    return amount


def get_number_of_lines():
    while True:
        lines = input(
            f"Enter the number of lines to bet on 1 - {MAX_LINES}:  "
        )

        if lines.isdigit():
            lines = int(lines)

            if 1 <= lines <= MAX_LINES:
                break
            else:
                print("Enter the valid number.")
        else:
            print("Lines should be entered as numbers")

    return lines


def get_bet():
    while True:
        bet = input(
            f"Enter the Amount of bet "
            f"({MIN_BET}$-{MAX_BET}$) on each line:  "
        )

        if bet.isdigit():
            bet = int(bet)

            if MIN_BET <= bet <= MAX_BET:
                break
            else:
                print(
                    f"Enter the bet Amount between "
                    f"${MIN_BET} - ${MAX_BET}"
                )
        else:
            print("Bet should be entered as numbers")

    return bet


def check_winnings(columns, lines, bet, values):
    winnings = 0
    winning_lines = []

    for line in range(lines):
        symbol = columns[0][line]

        if (
            columns[1][line] == symbol
            and columns[2][line] == symbol
        ):
            winnings += values[symbol] * bet
            winning_lines.append(line + 1)

    return winnings, winning_lines


def get_next_action():
    while True:
        action = input(
            "\nPress ENTER to spin again "
            "or type Q to quit: "
        ).lower()

        if action == "" or action == "q":
            return action

        print("Invalid input! Press ENTER or type Q.")


def main():
    balance = deposit()

    while True:

        print(f"\nYour current balance is: ${balance}")

        lines = get_number_of_lines()

        while True:
            bet = get_bet()

            total_bet = bet * lines

            if total_bet > balance:
                print(
                    f"Insufficient balance! "
                    f"Your current balance is ${balance}"
                )
            else:
                break

        print(
            f"\nYou are betting ${bet} on {lines} lines"
        )
        print(
            f"Your total bet amount is ${total_bet}"
        )

        # Spin the slot machine
        slots = get_slot_machine_spin(
            ROWS,
            COLS,
            symbol_count
        )

        print("\n***** SPIN *****\n")

        print_slot_machine(slots)

        # Check winnings
        winnings, winning_lines = check_winnings(
            slots,
            lines,
            bet,
            symbol_value
        )

        # Remove bet from balance
        balance -= total_bet

        # Add winnings
        balance += winnings

        if winnings > 0:
            print(
                f"\nCongratulations! 🎉 "
                f"You won ${winnings}"
            )
            print(
                f"Winning lines: {winning_lines}"
            )
        else:
            print("\nSorry! You didn't win anything.")

        print(f"Your new balance is: ${balance}")

        # Check if balance is enough to continue
        if balance < MIN_BET:
            print(
                "\nYou don't have enough balance "
                "to continue."
            )
            print(f"You are taking home ${balance}")
            break

        # Ask whether to continue
        action = get_next_action()

        if action == "q":
            print(
                f"\nThanks for playing!"
            )
            print(
                f"You are taking home ${balance}"
            )
            break


main()