MAX_LINES = 3
MAX_BET = 100        #Here capitals are constants...
MIN_BET = 30


ROWS = 3
COLS = 3

print("*****Welcome to Slot machine!!!*****")

symbol_count = {
    'A': 2,
    'B': 4,
    'C': 6,
    'D': 8
}

# ............................................................
#This functions are Generated by AI
def get_slot_machine_spin(rows, cols, symbols):   #This func is for spin for symbol count 
    all_symbols = []
    for symbol, symbol_count in symbols.items():
        for _ in range(symbol_count):
            all_symbols.append(symbol)
    columns = []
    for _ in range(cols):
        column = []
        current_symbols = all_symbols[:]
        for _ in range(rows):
            value = random.choice(current_symbols)
            current_symbols.remove(value)
            column.append(value)
        columns.append(column)
    return columns

def print_slot_machine(columns):             #This func is called for transpose the given matrix
    for row in range(len(columns[0])):
        for i, column in enumerate(columns):
            if i != len(columns) - 1:
                print(column[row], "|")
            else:
                print(column[row])
# .............................................................

def deposit():
    while True:
        amount = input("Enter your deposit: $")   #blud we can do directly but if the value is not int then it gives error (in int(input))
        if amount.isdigit():
            amount= int(amount)
            if amount > 0:
                break
            else:
                print("Amount should be greater then 0!")
        else:
            print("Amount should be entered as numbers")
    return amount


def get_number_of_lines():
    while True:
            lines = input(f"Enter the number of lines to bet on 1 - {MAX_LINES}:  ")
            if lines.isdigit():
                lines= int(lines)
                if 1 <= lines <= MAX_LINES:
                    break
                else:
                    print("Enter the valid number.")
            else:
                print("lines should be entered as numbers")
    return lines

def get_bet():
    while True:
        bet = input(f"Enter the Amount of bet ({MIN_BET}$-{MAX_BET}$) on each line:  ")
        if bet.isdigit():
            bet= int(bet)
            if MIN_BET <= bet <= MAX_BET:
                break
            else:
                print(f"Enter the bet Amount between ${MIN_BET} - ${MAX_BET}")
        else:
            print("Bet should be entered as numbers")
    return bet


def main():
    balance = deposit()
    lines = get_number_of_lines()
    while True:
        bet = get_bet()
        Total_bet = bet*lines
        if Total_bet > balance:
            print(f"Insufficiant balance ! your current balance is ${balance}")
        else:
            break
    print(f"You are betting ${bet} on {lines} lines and Your total bet amount is {Total_bet}$")
    print(balance , lines,bet)

main()